### ISSUE TITLE
Now I can't start the server...

### ISSUE THREAD

**Issue by Bodge-IT** [sandysound/orvibo-b25-server#10]
Looks like a folder issue:
pi@lofty:~/node_modules $ npm start
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v2.14.7
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node_modules/npm-debug.log

I installed into /home/pi with npm i orvibo-b25-server
Something's not right

**Comment by sandysound** [comment]
Hi, it looks like you're running the start command in the wrong folder.
If you've installed via npm and you're wanting to run the example script you will have run it from inside the /home/pi/node_modules/orvibo-b25-server 
If you're wanting to just use the server example you can also just call point node to the Example.js file like this ```node node_modules/orvibo-b25-server/Example.js``` rather than running the npm start command

**Comment by Bodge-IT** [comment]
Hi @sandysound, thanks v much for your support. I tried that, which worked sort of...
I had to enter the full path:
node /home/user/node_modules/orvibo-b25-server/Example.js
now it says:
Please pass Orvibo PK key details via the constructor or add to OrviboSettings.js file. See Readme
but it's already set in there along with a mac for one of my switches.

**Comment by sandysound** [comment]
If you've added the key to the OrviboSettings.js file this will be overwritten by the value settings object which is passed to the constructor in the Example.js file.
The easiest way to fix this is just to remove the settings object.
so change
```
let orvibo = new Orvibo(settings); 
```
to 
```
let orvibo = new Orvibo(); 
```
or add your key and plug info the the settings object in the Example.js file

**Comment by Bodge-IT** [comment]
Aha!  Easy when you know how.  thanks so much.

I'm going to try to use this with node-red.  Anything I need to watch out for?
